# Generated by Django 4.1.7 on 2023-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='label',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
