# Generated by Django 4.1.7 on 2023-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
